//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs_bazy_comic
{
    using System;
    using System.Collections.Generic;
    
    public partial class webtoon
    {
        public int series_id { get; set; }
        public string title { get; set; }
        public string status { get; set; }
        public string main_category { get; set; }
        public Nullable<System.DateTime> date_of_publication { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> o_publisher_id { get; set; }
        public Nullable<int> f_publisher_id { get; set; }
    
        public virtual author author { get; set; }
        public virtual for_publishers for_publishers { get; set; }
        public virtual orig_publishers orig_publishers { get; set; }
    }
}
